import { motion } from "framer-motion";
import { GlassCard } from "@/components/scam/GlassCard";
import { RiskGauge } from "@/components/scam/RiskGauge";
import { Button } from "@/components/ui/button";
import { RISK_META, scoreToLevel, type RiskLevel } from "@/lib/mock-data";
import { Sparkles, ShieldAlert, CheckCircle2, AlertTriangle, Download } from "lucide-react";
import type { ReactNode } from "react";
import { jsPDF } from "jspdf";

function downloadReport(result: ScanResult) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const meta = RISK_META[result.level];
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("ScamShield Report", margin, 56);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(new Date().toLocaleString(), margin, 74);

  y = 130;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Risk Score", margin, y);
  doc.setFontSize(36);
  doc.text(`${result.score}/100`, margin, y + 44);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Threat Level: ${meta.label}`, margin, y + 66);

  y += 110;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("AI Summary", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const summary = doc.splitTextToSize(result.aiSummary ?? "", pageW - margin * 2);
  doc.text(summary, margin, y);
  y += summary.length * 13 + 16;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Key Findings", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  result.findings.forEach((f) => {
    const lines = doc.splitTextToSize(`• ${f}`, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 13 + 4;
  });

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Recommendations", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  result.recommendations.forEach((r) => {
    const lines = doc.splitTextToSize(`✓ ${r}`, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 13 + 4;
  });

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 130);
  doc.text("Generated by ScamShield • Mock report for demo purposes", margin, doc.internal.pageSize.getHeight() - 30);

  doc.save(`scamshield-report-${Date.now()}.pdf`);
}

export interface ScanResult {
  score: number;
  level: RiskLevel;
  findings: string[];
  recommendations: string[];
  aiSummary?: string;
  extras?: ReactNode;
}

// ---------- Deterministic content-aware analyzer ----------

interface Signal {
  points: number;
  finding: string;
  recommendation?: string;
}

const SAFE_DOMAINS = [
  "github.com", "google.com", "microsoft.com", "apple.com", "amazon.com",
  "wikipedia.org", "stripe.com", "vercel.com", "cloudflare.com", "openai.com",
  "dropbox.com", "linkedin.com", "youtube.com", "netflix.com", "paypal.com",
  "hdfcbank.com", "icicibank.com", "sbi.co.in",
];

const BRAND_TOKENS = ["paypal", "amazon", "amaz0n", "paypa1", "hdfc", "icici", "sbi", "netflix", "apple", "microsoft", "google", "facebook", "instagram", "whatsapp"];
const SHORTENERS = ["bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly", "is.gd", "rebrand.ly", "cutt.ly", "shorturl.at"];
const SUSPICIOUS_TLDS = [".zip", ".mov", ".top", ".xyz", ".click", ".win", ".loan", ".work", ".gq", ".tk", ".ml", ".cf", ".country", ".fit"];
const SCAM_PHRASES = [
  "verify your account", "verify kyc", "kyc pending", "kyc update",
  "urgent action", "urgent action required", "account suspended", "account will be suspended",
  "account has been suspended", "temporarily suspended", "click here", "click the link",
  "you have won", "congratulations", "gift card", "free crypto", "claim your prize",
  "limited time offer", "act now", "final notice", "verify immediately",
  "refund initiated", "refund of", "customs fee", "delivery pending", "package on hold",
  "otp", "share otp", "one-time password", "your pin", "share your pin",
  "bank account will be", "reactivate your account", "unusual activity",
];
const IP_URL_RE = /https?:\/\/\d{1,3}(\.\d{1,3}){3}/i;
const URL_RE = /https?:\/\/[^\s"'<>)]+/gi;
const EMAIL_RE = /\b[\w.+-]+@[\w-]+\.[\w.-]+\b/g;

function extractHostname(u: string): string | null {
  try {
    const url = new URL(u.startsWith("http") ? u : `http://${u}`);
    return url.hostname.toLowerCase();
  } catch { return null; }
}

function analyzeUrl(raw: string, signals: Signal[]) {
  const host = extractHostname(raw);
  if (!host) return;
  const isSafeDomain = SAFE_DOMAINS.some((d) => host === d || host.endsWith(`.${d}`));

  if (isSafeDomain) {
    signals.push({ points: -25, finding: `Domain ${host} is a well-known, reputable service.` });
  }
  if (IP_URL_RE.test(raw)) {
    signals.push({ points: 30, finding: "URL uses a raw IP address instead of a domain name.", recommendation: "Never enter credentials on raw-IP URLs." });
  }
  if (SHORTENERS.some((s) => host === s || host.endsWith(`.${s}`))) {
    signals.push({ points: 25, finding: `Link uses URL shortener (${host}) that hides the real destination.`, recommendation: "Expand shortened URLs before opening them." });
  }
  if (!isSafeDomain && SUSPICIOUS_TLDS.some((t) => host.endsWith(t))) {
    const tld = SUSPICIOUS_TLDS.find((t) => host.endsWith(t))!;
    signals.push({ points: 20, finding: `Domain uses low-reputation TLD (${tld}).` });
  }
  if (!isSafeDomain) {
    const brand = BRAND_TOKENS.find((b) => host.includes(b));
    const looksLikeTypo = brand && !SAFE_DOMAINS.some((d) => d.includes(brand!));
    if (looksLikeTypo) {
      signals.push({ points: 35, finding: `Domain impersonates a known brand ("${brand}") — likely typosquatting.`, recommendation: "Do NOT enter credentials — report as phishing." });
    }
    if (/[0-9]/.test(host.split(".")[0]) && /[a-z]/.test(host.split(".")[0]) && host.split(".")[0].length > 4) {
      signals.push({ points: 10, finding: "Subdomain mixes letters and digits — common phishing pattern." });
    }
    if ((host.match(/-/g)?.length ?? 0) >= 2) {
      signals.push({ points: 10, finding: "Domain contains multiple hyphens — often used to mimic real brands." });
    }
    if (host.split(".").length >= 4) {
      signals.push({ points: 8, finding: "Deeply nested subdomain — legitimate services rarely need this." });
    }
  }
  if (!raw.startsWith("https://") && raw.startsWith("http://")) {
    signals.push({ points: 12, finding: "Uses plain HTTP — traffic is not encrypted." });
  }
}

function analyzeEmailAddress(addr: string, signals: Signal[]) {
  const [, domain] = addr.toLowerCase().split("@");
  if (!domain) return;
  const isSafeDomain = SAFE_DOMAINS.some((d) => domain === d || domain.endsWith(`.${d}`));
  if (isSafeDomain) {
    signals.push({ points: -15, finding: `Sender domain ${domain} matches a legitimate service.` });
    return;
  }
  const brand = BRAND_TOKENS.find((b) => domain.includes(b));
  if (brand && !SAFE_DOMAINS.some((d) => d.includes(brand!))) {
    signals.push({ points: 30, finding: `Sender domain ${domain} mimics "${brand}" — likely spoofed.` });
  }
  if (SUSPICIOUS_TLDS.some((t) => domain.endsWith(t))) {
    signals.push({ points: 15, finding: `Sender uses low-reputation TLD (${domain}).` });
  }
  if ((domain.match(/-/g)?.length ?? 0) >= 2) {
    signals.push({ points: 8, finding: "Sender domain contains multiple hyphens." });
  }
}

export function mockAnalyze(target: string): ScanResult {
  const signals: Signal[] = [];
  const text = target;
  const lower = text.toLowerCase();

  // URLs
  const urls = text.match(URL_RE) ?? [];
  urls.forEach((u) => analyzeUrl(u, signals));
  // bare-domain heuristic if no full URL
  if (urls.length === 0) {
    const bare = text.match(/\b([a-z0-9-]+\.)+[a-z]{2,}\b/gi) ?? [];
    bare.slice(0, 2).forEach((b) => analyzeUrl(`http://${b}`, signals));
  }

  // UPI / non-http schemes (common in QR scams)
  const upi = text.match(/upi:\/\/pay\?[^\s]+/i);
  if (upi) {
    const params = new URLSearchParams(upi[0].split("?")[1] ?? "");
    const pa = params.get("pa") ?? "";
    const am = Number(params.get("am") ?? "0");
    signals.push({ points: 15, finding: `QR contains a UPI payment request to "${pa || "unknown VPA"}".`, recommendation: "Never approve UPI collect requests from unknown VPAs." });
    if (am >= 1000) signals.push({ points: 15, finding: `Requests a large amount (₹${am}).` });
    if (/fraud|scam|test|xxx|abc\d+/i.test(pa)) signals.push({ points: 30, finding: `VPA "${pa}" matches known fraudulent pattern.` });
  }

  // Emails
  const emails = text.match(EMAIL_RE) ?? [];
  emails.forEach((e) => analyzeEmailAddress(e, signals));

  // Scam phrases
  const phraseHits = SCAM_PHRASES.filter((p) => lower.includes(p));
  if (phraseHits.length) {
    signals.push({
      points: Math.min(40, 10 + phraseHits.length * 8),
      finding: `Contains ${phraseHits.length} known scam phrase${phraseHits.length > 1 ? "s" : ""}: "${phraseHits.slice(0, 3).join('", "')}".`,
      recommendation: "Treat urgency/reward language as a red flag.",
    });
  }

  // Money / OTP / KYC signals
  if (/₹|rs\.?\s?\d|inr\s?\d|\$\d|usd\s?\d/i.test(text) && /(win|won|claim|prize|reward|refund|gift)/i.test(text)) {
    signals.push({ points: 20, finding: "Mentions money reward or refund — classic bait pattern." });
  }
  if (/\botp\b|one[- ]time\s+password/i.test(text)) {
    signals.push({ points: 15, finding: "Requests an OTP — legitimate businesses never ask for OTPs.", recommendation: "Never share OTPs with anyone." });
  }
  if (/24\s*hours|within\s*\d+\s*(min|hour)|immediately|right now|expires today/i.test(lower)) {
    signals.push({ points: 12, finding: "Uses time-pressure tactics to force fast action." });
  }
  if (/[A-Z]{6,}/.test(text) && text.length < 400) {
    signals.push({ points: 5, finding: "Excessive uppercase — common scam formatting." });
  }
  if (/!{2,}/.test(text)) {
    signals.push({ points: 4, finding: "Repeated exclamation marks indicate low-quality bulk message." });
  }
  if (/click (here|now|the link)/i.test(text)) {
    signals.push({ points: 8, finding: "Generic 'click here' call-to-action instead of a named destination." });
  }

  // Score
  const base = 8;
  const raw = signals.reduce((s, x) => s + x.points, base);
  const score = Math.max(3, Math.min(98, Math.round(raw)));
  const level = scoreToLevel(score);

  let findings = signals.filter((s) => s.points > 0).map((s) => s.finding);
  const positives = signals.filter((s) => s.points < 0).map((s) => s.finding);
  if (findings.length === 0) {
    findings = positives.length
      ? positives
      : [
          "No known scam patterns detected in the content.",
          "No suspicious URLs, brand impersonation, or urgency triggers found.",
          "Content structure looks consistent with legitimate communication.",
        ];
  }

  const recs = signals.map((s) => s.recommendation).filter((r): r is string => !!r);
  const recommendations = recs.length
    ? Array.from(new Set(recs))
    : score > 60
    ? [
        "Do not click any links or reply.",
        "Report the message to your security team or the platform.",
        "Delete or block the sender.",
      ]
    : score > 30
    ? [
        "Verify the sender through an independent channel before acting.",
        "Hover over links to confirm the real destination.",
        "When in doubt, contact the organization directly.",
      ]
    : [
        "Content appears safe — continue with normal caution.",
        "Always double-check URLs before entering credentials.",
      ];

  const aiSummary =
    score > 60
      ? `High-confidence scam signal. Analyzer matched ${findings.length} risk indicator${findings.length > 1 ? "s" : ""} including ${signals.filter((s) => s.points >= 20).length} strong flag${signals.filter((s) => s.points >= 20).length === 1 ? "" : "s"}. Treat this as malicious.`
      : score > 30
      ? `Mixed signals. Analyzer found ${findings.length} suspicious pattern${findings.length > 1 ? "s" : ""} but no definitive proof of a scam. Verify independently before trusting the content.`
      : `No meaningful threat signals detected. ${positives.length ? "Positive reputation indicators were also found." : "Content appears legitimate."}`;

  return { score, level, findings, recommendations, aiSummary };
}

export function ResultView({ result }: { result: ScanResult }) {
  const meta = RISK_META[result.level];
  const Icon = result.score > 60 ? ShieldAlert : result.score > 30 ? AlertTriangle : CheckCircle2;
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}
      className="grid gap-6 lg:grid-cols-3"
    >
      <GlassCard className="flex flex-col items-center justify-center text-center">
        <RiskGauge score={result.score} />
        <div className={`mt-6 flex items-center gap-2 rounded-full border px-3 py-1 text-sm ${meta.bg} ${meta.color}`}>
          <Icon className="h-4 w-4" /> Threat level: {meta.label}
        </div>
        <Button
          onClick={() => downloadReport(result)}
          variant="outline"
          className="mt-6 w-full border-white/10 bg-white/5 hover:bg-white/10"
        >
          <Download className="mr-2 h-4 w-4" /> Download PDF report
        </Button>
      </GlassCard>

      <GlassCard className="lg:col-span-2">
        <div className="flex items-center gap-2">
          <div className="grid h-8 w-8 place-items-center rounded-lg gradient-primary">
            <Sparkles className="h-4 w-4 text-white" />
          </div>
          <h3 className="font-bold">AI Analysis</h3>
          <span className="ml-auto text-xs text-muted-foreground">Powered by ScamShield AI</span>
        </div>
        <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{result.aiSummary}</p>
        <div className="mt-6 grid gap-4 md:grid-cols-2">
          <div>
            <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Key findings</div>
            <ul className="space-y-2 text-sm">
              {result.findings.map((f) => (
                <li key={f} className="flex gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                  <span>{f}</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Recommendations</div>
            <ul className="space-y-2 text-sm">
              {result.recommendations.map((r) => (
                <li key={r} className="flex gap-2">
                  <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-safe" />
                  <span>{r}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
        {result.extras}
      </GlassCard>
    </motion.div>
  );
}

export function LoadingScan({ label = "Scanning" }: { label?: string }) {
  return (
    <GlassCard className="flex flex-col items-center py-16 text-center">
      <div className="relative">
        <div className="h-24 w-24 rounded-full border-4 border-white/10 border-t-primary animate-spin" />
        <div className="absolute inset-0 grid place-items-center">
          <Sparkles className="h-8 w-8 text-accent animate-pulse" />
        </div>
      </div>
      <div className="mt-6 font-bold">{label}...</div>
      <div className="text-sm text-muted-foreground">Cross-checking 40+ threat intelligence feeds</div>
      <div className="mt-6 h-1 w-64 overflow-hidden rounded-full bg-white/5">
        <div className="h-full w-1/3 gradient-primary shimmer" />
      </div>
    </GlassCard>
  );
}

// helper for callers
export { scoreToLevel };
